### PR TITLE
C1200 get_vpn_status and set_vpn

### PR DESCRIPTION
**Pull request by swwgames**
This code pulls vpn data from the c1200 router. I also added a test method that checks the get_vpn_status and set_vpn functions.
Let me know if you want me to change something.

### CODE REVIEW

**Comment by AlexandrErohin** [comment]
@swwgames Thank you!

**Comment by AlexandrErohin** [comment]
@swwgames Hi.
I have moved your get_vpn_status and set_vpn functions to  TplinkBaseRouter class to use them for c6u routers
Could you test please these get_vpn_status and set_vpn functions in the new package version?
Thank you!

**Comment by swwgames** [comment]
Hi, @AlexandrErohin,
I tested your new version, version 5.9.0. And both functions, `get_vpn_status` and `set_vpn` work like before. Everything looks fine!

**Comment by AlexandrErohin** [comment]
@swwgames Thank you!

**Pull request merged**
