### PR TITLE
Added Ability to Change Wireless Settings for Archer C1200 and Fixed Issue with `set_wifi`

### PR DESCRIPTION
**Pull request by swwgames**
### Summary
- Added support for changing various wireless settings on the Archer C1200 router.
- Fixed an issue with the Archer C1200 router where `set_wifi` could not toggle the Wi-Fi radios on and off.

### Changes
- Duplicated the `set_wifi` function and placed it under the `TplinkC1200Router` class.
- Added the ability to specify multiple wireless settings; at least one setting must be provided.
- Modified the request path to include data in the URL, which is required by the C1200 router.

### Details
Previously, the `set_wifi` function used the following path:
```python
path = f"admin/wireless?&form=guest&form={value}"
```
The Archer C1200 router requires the path to be in this format:
```python
path = f"admin/wireless?form={value}&{data}"
```
This change ensures that the function works correctly with the C1200 router.

### Usage
Here is an example of how to use the updated `set_wifi` function:
```python
router.set_wifi(
    wifi=Connection.HOST_2G,
    enable=True,
    ssid="SSID",
    hidden="off",
    encryption="psk",
    psk_version="auto",
    psk_cipher="auto",
    psk_key="PASSWORD",
    hwmode="bgn",
    htmode="40",
    channel=1,
    txpower="high",
    disabled_all="off"
)
```
Note: Not all options need to be specified; however, `wifi` is necessary and at least one additional setting must be provided.

### Compatibility
While this code is for the Archer C1200, it should work for other routers with slight modifications. Specifically, the original `set_wifi` function's path includes `form=guest`, which might need to be added for different models.
I did not add this because i can't test it.

### CODE REVIEW

**Comment by swwgames** [comment]
Yes `router.set_wifi(Connection.HOST_2G, True)` will work, it will turn on the 2G band.
I also added a test for the set_wifi function. In the other pull request #29  I pasted my test file so far, Do I need to add all the other tests or are these enough?
```
class TestTPLinkClient(unittest.TestCase):

    def test_set_wifi(self) -> None:

        class TPLinkRouterTest(TplinkC1200Router):
            def request(self, path: str, data: str,
                        ignore_response: bool = False, ignore_errors: bool = False) -> dict | None:

                self.captured_path = path
                self.captured_data = data

        client = TPLinkRouterTest('', '')
        client.set_wifi(
            Connection.HOST_5G,
            enable=True,
            ssid="TestSSID",
            hidden="no",
            encryption="WPA3-PSK",
            psk_version="2",
            psk_cipher="AES",
            psk_key="testkey123",
            hwmode="11ac",
            htmode="VHT20",
            channel=36,
            txpower="20",
            disabled_all="no"
        )
        
        expected_data = ("operation=write&enable=on&ssid=TestSSID&hidden=no&encryption=WPA3-PSK&"
                         "psk_version=2&psk_cipher=AES&psk_key=testkey123&hwmode=11ac&"
                         "htmode=VHT20&channel=36&txpower=20&disabled_all=no")
        expected_path = f"admin/wireless?form=wireless_5g&{expected_data}"
        
        self.assertEqual(client.captured_path, expected_path)
        self.assertEqual(client.captured_data, expected_data)
```

**Comment by AlexandrErohin** [comment]
@swwgames 
Could you resolve conflicts please

**Comment by AlexandrErohin** [comment]
@swwgames Thank you!

**Comment by deepakkoirala** [comment]
Please update the documentation on how to enable/disable the wifi , change wifi ssid and password ?

**Pull request merged**
